### ISSUE TITLE
scripts in the distribution don't work

### ISSUE THREAD

**Issue by szabgab** [graphviz-perl/GraphViz2-Parse-ISA#1]
I've installed the module with `cpanm GraphViz2::Parse::ISA` then downloaded the source: `wget https://cpan.metacpan.org/authors/id/E/ET/ETJ/GraphViz2-Parse-ISA-2.52.tar.gz` and unzipped it.

```
$ perl scripts/dependency.pl 
Can't locate object method "dependency" via package "GraphViz2" at scripts/dependency.pl line 31, <DATA> line 2066.
```

```
$ perl scripts/parse.isa.pl 
Can't open(> html/parse.isa.svg): No such file or directory at /home/gabor/perl5/lib/perl5/GraphViz2.pm line 625.
```

Maybe I am trying to use them incorrectly, but I could not find how should I use them.

**Comment by mohawk2** [comment]
Thanks for the report! The first script was obsoleted by the removed (never-documented) `dependency` method in `GraphViz2` and has now been removed.

The second one is failing because, exactly as the message says, you don't have an `html` directory. If you run the script with arguments like:

```
perl -Ilib scripts/parse.isa.pl svg output.svg
```

it will work.
